/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reservasihotel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author infinix
 */
public class MainForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainForm.class.getName());

    /**
     * Creates new form MainForm
     */
    public MainForm() {
    initComponents();
        cmbKamar.setModel(
            new javax.swing.DefaultComboBoxModel<>(
                new String[]{
                    "Standard",
                    "Deluxe",
                    "Suite"
                }
            )
        );
        txtTotal.setEditable(false);
        tblReservasi.setModel(
            new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nama",
                    "No Telepon",
                    "Email",
                    "Kamar",
                    "Lama Menginap",
                    "Total Biaya"
                }
            )
        );
        txtNama.setText("");
        txtTelepon.setText("");
        txtEmail.setText("");
        txtLama.setText("");
        txtTotal.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NamaPelanggan = new javax.swing.JLabel();
        NoTelepon = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        JenisKamar = new javax.swing.JLabel();
        LamaMenginap = new javax.swing.JLabel();
        TotalBiaya = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLama = new javax.swing.JTextField();
        cmbKamar = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Hari = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        btnReservasi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservasi = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NamaPelanggan.setText("Nama Pelanggan : ");

        NoTelepon.setText("No Telepon :");

        Email.setText("Email :");

        JenisKamar.setText("Jenis Kamar :");

        LamaMenginap.setText("Lama Menginap : ");

        TotalBiaya.setText("Total Biaya : ");

        txtNama.setText("txtNama");
        txtNama.addActionListener(this::txtNamaActionPerformed);

        txtTelepon.setText("txtTelepon");
        txtTelepon.addActionListener(this::txtTeleponActionPerformed);

        txtEmail.setText("txtEmail");
        txtEmail.addActionListener(this::txtEmailActionPerformed);

        txtLama.setText("txtLama");
        txtLama.addActionListener(this::txtLamaActionPerformed);

        cmbKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTotal.setEditable(false);
        txtTotal.setText("txtTotal");
        txtTotal.addActionListener(this::txtTotalActionPerformed);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("SISTEM RESERVASI HOTEL");

        Hari.setText("Hari");

        btnHitung.setText("Hitung Biaya");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        btnReservasi.setText("Reservasi");
        btnReservasi.addActionListener(this::btnReservasiActionPerformed);

        tblReservasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "No Telepon", "Email", "Kamar", "Lama Menginap", "Total Biaya"
            }
        ));
        tblReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblReservasi);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaPelanggan)
                            .addComponent(NoTelepon)
                            .addComponent(Email)
                            .addComponent(JenisKamar)
                            .addComponent(LamaMenginap)
                            .addComponent(TotalBiaya)
                            .addComponent(btnHitung))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnReservasi)
                                .addGap(45, 45, 45)
                                .addComponent(btnEdit)
                                .addGap(46, 46, 46)
                                .addComponent(btnHapus))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTelepon)
                                .addComponent(txtNama)
                                .addComponent(txtEmail)
                                .addComponent(cmbKamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtLama, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Hari))
                                .addComponent(txtTotal)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)))
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaPelanggan)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoTelepon)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JenisKamar)
                    .addComponent(cmbKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LamaMenginap)
                    .addComponent(txtLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalBiaya)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnReservasi)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleponActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLamaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            double harga = 0;
            String kamar = cmbKamar.getSelectedItem().toString();
            switch (kamar) {
                case "Standard":
                    harga = 300000;
                    break;
                case "Deluxe":
                    harga = 500000;
                    break;
                case "Suite":
                    harga = 800000;
                    break;
            }
            int lama = Integer.parseInt(txtLama.getText());
            double total = harga * lama;
            txtTotal.setText(String.valueOf(total));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Masukkan lama menginap dengan benar!");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
        if (txtNama.getText().isEmpty() || txtTelepon.getText().isEmpty() || txtEmail.getText().isEmpty()
                || txtLama.getText().isEmpty() || txtTotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi data terlebih dahulu!");
                return;
        }
        DefaultTableModel model =(DefaultTableModel)tblReservasi.getModel();
        model.addRow(new Object[]{
            txtNama.getText(),
            txtTelepon.getText(),
            txtEmail.getText(),
            cmbKamar.getSelectedItem(),
            txtLama.getText(),
            txtTotal.getText()
        });
        JOptionPane.showMessageDialog(this, "Reservasi berhasil disimpan!");
        txtNama.setText("");
        txtTelepon.setText("");
        txtEmail.setText("");
        txtLama.setText("");
        txtTotal.setText("");
        cmbKamar.setSelectedIndex(0);
    }//GEN-LAST:event_btnReservasiActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = tblReservasi.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this,"Pilih data terlebih dahulu!");
            return;
        }
        DefaultTableModel model =(DefaultTableModel)tblReservasi.getModel();
        model.setValueAt(txtNama.getText(),row,0);
        model.setValueAt(txtTelepon.getText(),row,1);
        model.setValueAt(txtEmail.getText(),row,2);
        model.setValueAt(cmbKamar.getSelectedItem(),row,3);
        model.setValueAt(txtLama.getText(),row,4);
        model.setValueAt(txtTotal.getText(),row,5);
        JOptionPane.showMessageDialog(this,"Data berhasil diubah!");
        txtNama.setText("");
        txtTelepon.setText("");
        txtEmail.setText("");
        txtLama.setText("");
        txtTotal.setText("");
        cmbKamar.setSelectedIndex(0);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tblReservasi.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this,"Pilih data yang akan dihapus!");
            return;
        }
        DefaultTableModel model =(DefaultTableModel)tblReservasi.getModel();
        model.removeRow(row);
        JOptionPane.showMessageDialog(this,"Data berhasil dihapus!");
        txtNama.setText("");
        txtTelepon.setText("");
        txtEmail.setText("");
        txtLama.setText("");
        txtTotal.setText("");
        cmbKamar.setSelectedIndex(0);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblReservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservasiMouseClicked
        int row = tblReservasi.getSelectedRow();
        txtNama.setText(tblReservasi.getValueAt(row, 0).toString());
        txtTelepon.setText(tblReservasi.getValueAt(row, 1).toString());
        txtEmail.setText(tblReservasi.getValueAt(row, 2).toString());
        cmbKamar.setSelectedItem(tblReservasi.getValueAt(row, 3).toString());
        txtLama.setText(tblReservasi.getValueAt(row, 4).toString());
        txtTotal.setText(tblReservasi.getValueAt(row, 5).toString());
    }//GEN-LAST:event_tblReservasiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Hari;
    private javax.swing.JLabel JenisKamar;
    private javax.swing.JLabel LamaMenginap;
    private javax.swing.JLabel NamaPelanggan;
    private javax.swing.JLabel NoTelepon;
    private javax.swing.JLabel TotalBiaya;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JComboBox<String> cmbKamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservasi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLama;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
